// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apbmqlcsbvvthzkxxxyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwYm1xbGNzYnZ2dGh6a3h4eHlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NDAxNzYsImV4cCI6MjA2NjAxNjE3Nn0.8Ia12DOOhT9C0KO6CPA3h_DJTlip6vYNlUuP-XMN8Yk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);